### ISSUE TITLE
facing issue while running this repository

### ISSUE THREAD

**Issue by khyatimehta11** [adiparamartha/LRFU-Replacement-Policy-using-ndnSIM#1]
I followed all steps that are mention in readme and also I tried to install ndnSIM 2.6 version through the link mentioned but that link is installing 2.8 version of ndnSIM instead of 2.6 and again I am alot of error occur while running ./waf command after copying all files of this project.

**Comment by adiparamartha** [comment]
Hi @khyatimehta11, thank you for using our work.
While you execute the ./waf command, usually there is an error generated.
But it is fine, depending on the error.

Could you attach the log or error condition?
Thanks

**Comment by khyatimehta11** [comment]
As you mentioned that this will run on 2.6 version but we can't find from where to download this version, can you please let us know from where to download 2.6 version, we tried to download via ndnSIM website but it downloads the 2.8 current version. We even tried to run this on 2.8 and we were getting a lot of errors related to file not found while running ./waf command.
Following are the files that are not found and because of which error occurred scheduler.cpp, scheduler.hpp, asserts.hpp, fib-max-depth.hpp and many more
where we can get this files as these are not there in this project. Can you please guide us on this so that we can proceed with the work.

**Comment by adiparamartha** [comment]
Hi, @khyatimehta11 sorry for the late reply.
Due to the old version I'm using at that time, please refer to the following NDN version from their website.
[ndnSIM 2.6](https://ndnsim.net/2.6/).

After you try to install that specific version of ndnSIM, please give me an update.
Thankyou
